version: '3.8'

services:
  app:
    build: .
    container_name: express-ts-app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

volumes:
  mysql-data:
